version: '3'
services:
  web1:
    image: php:8.2-apache
    container_name: web1
    ports:
      - "8090:80"
    volumes:
      - /var/www/html:/var/www/html
      - php-logs:/var/log/apache2
  web2:
    image: php:8.2-apache
    container_name: web2
    ports:
      - "8081:80"
    volumes:
      - /var/www/html:/var/www/html
      - php-logs:/var/log/apache2
volumes:
  php-logs: